// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: proto/communication.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        float32 `protobuf:"fixed32,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Arg1      float32 `protobuf:"fixed32,2,opt,name=Arg1,proto3" json:"Arg1,omitempty"`
	Arg2      float32 `protobuf:"fixed32,3,opt,name=Arg2,proto3" json:"Arg2,omitempty"`
	Operation string  `protobuf:"bytes,4,opt,name=Operation,proto3" json:"Operation,omitempty"`
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_communication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_communication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetID() float32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TaskRequest) GetArg1() float32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *TaskRequest) GetArg2() float32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *TaskRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type SendTaskMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        float32 `protobuf:"fixed32,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Arg1      float32 `protobuf:"fixed32,2,opt,name=Arg1,proto3" json:"Arg1,omitempty"`
	Arg2      float32 `protobuf:"fixed32,3,opt,name=Arg2,proto3" json:"Arg2,omitempty"`
	Operation string  `protobuf:"bytes,4,opt,name=Operation,proto3" json:"Operation,omitempty"`
}

func (x *SendTaskMessage) Reset() {
	*x = SendTaskMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_communication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTaskMessage) ProtoMessage() {}

func (x *SendTaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_communication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTaskMessage.ProtoReflect.Descriptor instead.
func (*SendTaskMessage) Descriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{1}
}

func (x *SendTaskMessage) GetID() float32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SendTaskMessage) GetArg1() float32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *SendTaskMessage) GetArg2() float32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *SendTaskMessage) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type UpdateTaskStringMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     float32 `protobuf:"fixed32,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Result float32 `protobuf:"fixed32,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Status string  `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *UpdateTaskStringMessage) Reset() {
	*x = UpdateTaskStringMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_communication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTaskStringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStringMessage) ProtoMessage() {}

func (x *UpdateTaskStringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_communication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStringMessage.ProtoReflect.Descriptor instead.
func (*UpdateTaskStringMessage) Descriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTaskStringMessage) GetID() float32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateTaskStringMessage) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *UpdateTaskStringMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_communication_proto protoreflect.FileDescriptor

var file_proto_communication_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x22, 0x63, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x41, 0x72, 0x67, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x32, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x41, 0x72, 0x67, 0x32, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x67, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x41,
	0x72, 0x67, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x41, 0x72, 0x67, 0x31, 0x12,
	0x12, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x41,
	0x72, 0x67, 0x32, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x59, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x91, 0x01, 0x0a,
	0x0b, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x08,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x48, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44,
	0x41, 0x4e, 0x43, 0x48, 0x49, 0x4b, 0x31, 0x32, 0x31, 0x2f, 0x59, 0x41, 0x4e, 0x44, 0x45, 0x58,
	0x2d, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x6c, 0x79, 0x2d, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x2d, 0x50, 0x61, 0x72, 0x74, 0x2d, 0x32, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_communication_proto_rawDescOnce sync.Once
	file_proto_communication_proto_rawDescData = file_proto_communication_proto_rawDesc
)

func file_proto_communication_proto_rawDescGZIP() []byte {
	file_proto_communication_proto_rawDescOnce.Do(func() {
		file_proto_communication_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_communication_proto_rawDescData)
	})
	return file_proto_communication_proto_rawDescData
}

var file_proto_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_communication_proto_goTypes = []any{
	(*TaskRequest)(nil),             // 0: server.TaskRequest
	(*SendTaskMessage)(nil),         // 1: server.SendTaskMessage
	(*UpdateTaskStringMessage)(nil), // 2: server.UpdateTaskStringMessage
}
var file_proto_communication_proto_depIdxs = []int32{
	0, // 0: server.TaskService.SendTask:input_type -> server.TaskRequest
	0, // 1: server.TaskService.UpdateTaskString:input_type -> server.TaskRequest
	1, // 2: server.TaskService.SendTask:output_type -> server.SendTaskMessage
	2, // 3: server.TaskService.UpdateTaskString:output_type -> server.UpdateTaskStringMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_communication_proto_init() }
func file_proto_communication_proto_init() {
	if File_proto_communication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_communication_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_communication_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SendTaskMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_communication_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTaskStringMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_communication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_communication_proto_goTypes,
		DependencyIndexes: file_proto_communication_proto_depIdxs,
		MessageInfos:      file_proto_communication_proto_msgTypes,
	}.Build()
	File_proto_communication_proto = out.File
	file_proto_communication_proto_rawDesc = nil
	file_proto_communication_proto_goTypes = nil
	file_proto_communication_proto_depIdxs = nil
}
